#+title: HPC with Julia: a short introduction
#+description: Hands-on
#+colordes: #8a2000
#+slug: 09_jl_hpc
#+weight: 9

* Jupyter vs SSH

** Limitations of Jupyter

Jupyter is a fantastic tool. It has a major downside however: when you launch a Jupyter session, you are running a job on a compute node. If you want to play for 8 hours in Jupyter, you are requesting an 8 hour job. Now, most of the time you spend on Jupyter is spent typing, running bits and pieces of code, or doing nothing at all. If you ask for GPUs, many CPUs, and lots of RAM, all of it will remain idle most of the time. This is a suboptimal use of resources.

In addition, if you ask for lots of resources for a long time, you will have to wait for a while before they get allocated to you.

You will also go through your allocations quickly.

Lastly, your notebook is running on a single node. It is thus not suitable to run distributed memory parallel tasks.

** A good approach

A pretty good strategy is to develop and test your code with small samples, few iterations, etc. in an interactive job (from an SSH session in the cluster with ~salloc~), on your own computer (if appropriate), or in Jupyter, *then*, launch an ~sbatch~ job from an SSH session in the cluster to run the full code. This ensures that heavy duty resources such as GPU(s) are only allocated to you when you are actually needing and using them.

This is exactly what we are doing during this workshop.

* Accessing Julia in an SSH session

** Log in the training cluster

First, [[https://westgrid-julia.netlify.app/autumnschool2020/01_jl_intro/#headline-3][SSH into our training cluster UU]]. This takes you to the login node of the cluster.

** Load necessary modules

This is done with the [[https://github.com/TACC/Lmod][Lmod]] tool through the [[https://docs.computecanada.ca/wiki/Utiliser_des_modules/en][module command]] (you can find the full documentation [[https://lmod.readthedocs.io/en/latest/010_user.html][here]]).

Below are some key [[https://lmod.readthedocs.io/en/latest/010_user.html][Lmod commands]]:

#+BEGIN_src sh
# Get help on the module command
$ module help

# List modules that are already loaded
$ module list

# See which modules are available for Julia
$ module spider julia

# See how to load the latest version (julia/1.5.2)
$ module spider julia/1.5.2

# Load julia/1.5.2 with the required StdEnv/2020 module first
# (the order is important)
$ module load StdEnv/2020 julia/1.5.2

# You can see that we now have Julia loaded
$ module list
#+END_src

* Job scripts

To submit a job to Slurm (the job scheduler used by the Compute Canada clusters), you need to write an {{<b>}}sbatch{{</b>}} script:

#+BEGIN_src sh
#!/bin/bash
#SBATCH --job-name=<name>			# job name
#SBATCH --time=<time>				# max walltime
#SBATCH --cpus-per-task=<n>         # number of cores
#SBATCH --mem=<mem>					# max memory (default unit is megabytes)
#SBATCH --output=<file%j.out>		# file name for the output
#SBATCH --error=<file%j.err>		# file name for errors
# %j gets replaced with the job number

<body>
#+END_src

To submit a job to the cluster:

#+BEGIN_src sh
$ cd /dir/containing/script
$ sbatch script.sh
#+END_src

And we can check its status with:

#+BEGIN_src sh
$ sq
#+END_src

{{<b>}}PD{{</b>}} stands for pending and {{<b>}}R{{</b>}} for running.

* Comments & questions
