#+title: Software installation
#+description: Practice
#+colordes: #dc7309
#+slug: jl-03-install
#+weight: 3

* Installing Julia

Download the current [[https://julialang.org/downloads/][Julia stable release]] and follow the [[https://julialang.org/downloads/platform/][installation instructions]] corresponding to your operating system.

* Installing a terminal emulator and SSH client

You will need a terminal emulator and an SSH client for remote access to the Compute Canada cluster.

If you took the course on [[https://wgschool.netlify.app/bash-menu/][Bash]] or [[https://wgschool.netlify.app/hpc-menu/][HPC]] last week, you are already set.\\
If not, follow the instructions for your OS:

{{<n>}}{{<s>}} /Windows:/ \\
{{<n>}}{{<n>}}Install the [[https://mobaxterm.mobatek.net/download.html][free Home Edition of MobaXTerm]].\\

{{<n>}}{{<s>}} /MacOS:/ \\
{{<n>}}{{<n>}}Terminal and SSH are pre-installed.

{{<n>}}{{<s>}} /Linux:/ \\
{{<n>}}{{<n>}}You can use xterm or the terminal emulator of your choice.\\
{{<n>}}{{<n>}}If SSH does not come bundled with your distribution, install [[https://www.openssh.com/][OpenSSH]].\\
{{<n>}}{{<n>}}(You can type {{<c>}}ssh{{</c>}} in the command line to see whether it is installed).

* Installing a text editor

Finally, you will need a capable text editor.\\
Examples include Emacs, Vim, Visual Studio Code, Sublime, Nano, Atom, Notepad++.\\
Note that Microsoft Notepad is too simplistic and WordPad is not a text editor.

Alternatively, if you would rather play in the [[https://junolab.org/][Julia IDE]], you can find the installation instructions [[http://docs.junolab.org/latest/man/installation][here]].{{<fl n="1">}}

* Important note

If you have issues with these installations{{<fl n="1">}}, please sign up for the [[https://westgrid-julia.netlify.app/school/jl-06-debug.html][debug session]] to make sure that you are set before our next Zoom meeting (we will not have time to debug installation issues during that meeting).

{{<fn>}}
{{<fr n="1" text="We will not debug the Juno IDE as its use is not part of this course. While you are welcome to use it, if you encounter problems with it, you will have to move to a text editor to edit your Julia code.">}}
{{</fn>}}

* Comments & questions
