#+title: Distributed computing
#+description: Zoom
#+colordes: #cc0066
#+slug: jl-12-distributed
#+weight: 12

#+OPTIONS: toc:nil

#+BEGIN_zoombox
*This interactive session will be conducted through Zoom.*

*The meeting ID and password will be emailed to people who registered for this course.*
#+END_zoombox

Note that *no recording* will be made during this session so as not to discourage participation.

* Launching several Julia processes

Julia supports distributed computing thanks to the module {{<b>}}Distributed{{</b>}} from its standard library.

There are two ways to launch several Julia processes (called "workers"):

**** Launch Julia on n workers

Julia can be started with the {{<c>}}-p{{</c>}} flag followed by the number of workers by running (in a terminal):

#+BEGIN_src sh
julia -p n
#+END_src

This launches {{<b>}}n{{</b>}} workers, available for parallel computations, in addition to the process running the interactive prompt (so there are {{<b>}}n + 1{{</b>}} Julia processes in total).

The module {{<b>}}Distributed{{</b>}} is needed whenever you want to use several workers, but the {{<c>}}-p{{</c>}} flag loads it automatically.

/Example:/

#+BEGIN_src sh
julia -p 4
#+END_src

Within Julia, you can see how many workers are running with:

#+BEGIN_src julia
nworkers()
#+END_src

The total number of processes can be seen with:

#+BEGIN_src julia
nprocs()
#+END_src

**** Start workers from within a Julia session

Alternatively, workers can be started from within a Julia session. In this case, you need to load the module {{<b>}}Distributed{{</b>}} explicitly:

#+BEGIN_src julia
using Distributed
#+END_src

To launch {{<b>}}n{{</b>}} workers:

#+BEGIN_src julia
addprocs(n)
#+END_src

/Example:/

#+BEGIN_src julia
addprocs(4)
#+END_src

**** Managing workers

To list all the worker process identifiers:

#+BEGIN_src julia
workers()
#+END_src

/Note:/ {{<s>}}The process running the Julia prompt has id {{<b>}}1{{</b>}}.

To kill a worker:

#+BEGIN_src julia
rmprocs(<pid>)
#+END_src

where {{<c>}}&lt;pid&gt;{{</c>}} is the process identifier of the worker you want to kill (you can kill several workers by providing a list of pids).
