#+title: Opening session
#+description: Zoom
#+colordes: #e86e0a
#+slug: 01_jl_intro
#+weight: 1

#+BEGIN_def
/Date:/ {{<m>}}{{<s>}} Tuesday, May 31 \\
/Time:/ {{<m>}}{{<s>}} 9:30 am Pacific Time \\
/Access:/ {{<m>}} You should have received the meeting id and password by email.

{{<notes>}}
Please have a look in your spam box if you haven't received the email.
{{</notes>}}
#+END_def

* Accessing our training cluster

** Open a terminal emulator

/Windows:/ {{<m>}}{{<s>}}[[https://mobaxterm.mobatek.net/][MobaXTerm]] (free Home Edition)\\
/MacOS:/ {{<m>}}{{<m>}}Terminal \\
/Linux/WSL:/ {{<s>}}{{<s>}}Your usual terminal emulator

** SSH into the cluster

#+BEGIN_note
If you were with us for the Python course last week, you can use the same usernames and passwords.
Otherwise, those will be given to you during the Zoom session.
#+END_note
{{<br size="3">}}

- Linux, WSL, and MacOS type in your terminal:

#+BEGIN_src sh
$ ssh userxxx@uu.c3.ca
# enter password (it is blind typing, so you won't see it as you type)
#+END_src

- Window users:

{{<a "https://mobaxterm.mobatek.net/demo.html" "This demo">}} shows how to use SSH with MobaXterm (for "Remote host" enter: ~uu.c3.ca~).

* Running Julia

** Load the Julia module

To see which versions of Julia are available on the cluster:

#+BEGIN_src sh
$ module spider julia
#+END_src

To load one of the modules (e.g. ~julia/1.3.0~), we first need to know what its dependencies are:

#+BEGIN_src sh
$ module spider julia/1.3.0
#+END_src

We can then load the dependencies and the Julia module:

#+BEGIN_src sh
$ module load nixpkgs/16.09 gcc/7.3.0 julia/1.3.0
#+END_src

** Start an interactive job

#+BEGIN_src sh
$ salloc --time=03:00:00 --mem=11250
#+END_src

** Launch Julia

Finally, we can launch the Julia REPL by running the `julia` command:

#+BEGIN_src sh
$ julia
#+END_src

* Comments & questions
